/vis/verbose 0
/vis/open OGL 600x600-0+0
/vis/viewer/set/autoRefresh false

# Draw geometry:
/vis/drawVolume

# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0
/vis/viewer/set/style surface

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set neutron grey
/vis/modeling/trajectories/drawByParticleID-0/set alpha red

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate 50
/vis/viewer/set/background white
# Decorations
/vis/set/textColour red
/vis/set/textLayout right
#/vis/scene/add/text2D 0.9 -.9 24 ! ! NeutronDet

# Axes
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
/vis/scene/add/date    # Date stamp
/vis/scene/add/logo2D  # Simple logo

#/vis/geometry/set/visibility world_log 0 false
/vis/viewer/set/style wireframe
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 120 150
#/vis/viewer/set/upVector 0 1 0
#/vis/viewer/set/upThetaPhi 90 -90 deg
#/vis/viewer/set/viewpointThetaPhi 90 -90 deg



#/vis/viewer/set/viewpointVector 0 -1 0
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true

